using Ardalis.Result;
using MediatR;
using System;

namespace TNK.UseCases.AvailabilitySlots.Generate;

public record GenerateAvailabilitySlotsCommand(
    Guid WorkerId,
    int BusinessProfileId,       // For authorization
    DateOnly StartDate,
    DateOnly EndDate,
    Guid? ScheduleId = null,     // Optional: If null, use worker's default schedule
    int SlotDurationInMinutes = 30, // Default slot duration
                                    // Determines how to handle existing slots in the range for this worker.
                                    // True: Deletes unbooked slots previously generated by *any* schedule.
                                    // False: Attempts to generate slots only in empty spaces (more complex).
                                    // Consider refining this strategy.
    bool OverwriteExistingGeneratedUnbookedSlots = true
) : IRequest<Result<int>>; // Returns the count of slots generated
